#ifndef PERIPHERAL_DW_APB_SSI_H
#define PERIPHERAL_DW_APB_SSI_H

#include <io/types.h>

struct SSI_CONTROLLER {
    VU32 CTRL0;
    VU32 CTRL1;
    VU32 ENABLE;
    VU32 MW_CTRL;
    VU32 SLAVE_ENABLE;
    VU32 BAUD;
    VU32 TX_FIFO_TL;
    VU32 RX_FIFO_TL;
    VU32 TX_FIFO_LVL;
    VU32 RX_FIFO_LVL;
    VU32 STATUS;
    VU32 INT_MASK;
    VU32 INT_STATUS;
    VU32 RAW_INT_STATUS;
    VU32 TX_FIFO_OVERFLOW_ICR;
    VU32 RX_FIFO_OVERFLOW_ICR;
    VU32 RX_FIFO_UNDERFLOW_ICR;
    VU32 MULTI_MASTER_ICR;
    VU32 ICR;
    VU32 DMA_CONTROL;
    VU32 DMA_TX_DATA_LVL;
    VU32 DMA_RX_DATA_LVL;
    VU32 ID;
    VU32 COMP_VERSION;
    VU32 DR[36];
    VU32 RX_SAMPLE_DELAY;
    VU32 RESERVED[3];
};

#endif
